branches:
  only:
    - master

language: python

python:
  - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y xsltproc
    - sudo apt-get install -y genisoimage

install:
  - pip install -r .travis.requirements.txt

script: ./.travis.script
