language: python

branches:
    except:
        - gh-pages

matrix:
    include:
        - python: 3.4
          env: TOXENV=3.4,check,doc_travis
        - python: 3.5
          env: TOXENV=3.5,check,doc_travis


before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y xsltproc
    - sudo apt-get install -y genisoimage
    - sudo apt-get install -y enchant

install:
    - pip install -r .travis.requirements.txt

script:
    - tox

after_success:
    - tox -e doc_travis_deploy
