language: python

branches:
    except:
        - gh-pages

matrix:
    include:
        - python: 3.4
          env: TOXENV=3.4
        - python: 3.5
          env: TOXENV=3.5


before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y xsltproc
    - sudo apt-get install -y genisoimage

install:
    - pip install -r .travis.requirements.txt

script:
    - tox

after_success:
    - travis-sphinx -n --source doc/source build
    - travis-sphinx deploy
