language: python

branches:
    except:
        - gh-pages

matrix:
    include:
        - python: 3.4
          env: TOXENV=3.4,check,doc_travis
        - python: 2.7
          env: TOXENV=2.7,check,doc_travis


before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y xsltproc
    - sudo apt-get install -y genisoimage
    - sudo apt-get install -y enchant

install:
    - pip install -r .travis.requirements.txt

script:
    - tox

after_success:
    - tox -e doc_travis_deploy

deploy:
  provider: pypi
  user: suse
  password:
    secure: "D5pCJcdIxC9c6zdh0qog1Ks57Znuk4XjyF/1p90FC5Lv+FD1QPwPAxl/TDwCTI4YEMXrv7tXAVsyiOBz3qXj8Odj0hcAMGcQMD6ymsnIRWFrZ928o2faVTWHGoW0yk4d2/n7Q0d505zr+r9xJ0FBsmrF0/Clf0AJLOJ31rexQUGHZ9jmSIkrrkpFsHiP8RjtsfaB019NYZUwyBOiffdH1E4x9Ucb6N3pWL+IzK82jJzEtAxJdh1zgWDcmAX56deRXGRbNt8qJqJY1PRM7EfEfMyzcSAFe4WlgxltfFqhVk1eBxC5+Soq+uHOw/eP1ov+crjiOruokb2vIeAMyjW2DcSXOVNUYO3obvbAI4fydx5giC1MYiRwNlu4NZWQQ63ZtZhH9gCKWpxDG26W7rMpcILAMzMevpqN+3MoRpwmazmKFnbmOydq1WVwOEwGMl7PNNL2Pm4zUayCeNbhmKI+01bmVAmAnyS4XU/byOYtYntFohuPRF/QD3nuUkaoXQEswP5C/JlhLFKYxNm5BrIHOwQzodnIuSVJfdnHExdAWJFY+Us2pAVuQkBKZtvYG7GMSP8Xxv9wYq2VryGPGsThaAyHSV36ARpHt5zRetcsb7Lw0zuj8cpwi4L+yhUc0mHtbga6ABGsm+1YF5VhqZqDRmpZK7wjoq3fEiyr4iJQ+jY="
    on:
      tags: true
      branch: master
